version: 2
jobs:
  build:

    docker:
      - image: ocaml/opam2

    steps:
      - checkout

      - run:
          name: Install OCaml packages
          command: |
            sudo apt-get install -y m4
            opam update
            opam install .

      - run:
          name: Build Seashell and run examples
          command: |
            eval $(opam env)
            make
            make test
