version: 2
jobs:
  build:

    docker:
      - image: ocaml/opam

    steps:
      - checkout

      - run:
          name: Install OCaml packages
          command: opam install -y ounit menhir dune

      - run:
          name: Build Seashell
          command: dune build bin/ex.bc
