version: 2
jobs:
  build:

    docker:
      - image: ocaml/opam

    steps:
      - checkout

      - run:
          name: Install OCaml/OPAM/m4
          command: sudo apt-get install m4 ocaml opam

      - run:
          name: Configure OPAM
          command: opam init -a -y; opam switch -y 4.05.0; eval `opam config env`

      - run:
          name: Install OCaml packages
          command: opam install -y ounit menhir dune; opam user-setup install

      - run:
          name: Build Seashell
          command: dune build bin/ex.bc
