version: 2
jobs:
  build:

    docker:
      - image: ocaml/opam2

    steps:
      - checkout

      - run:
          name: Install OCaml packages
          command: sudo apt-get install -y m4 && opam install -y ounit menhir dune

      - run:
          name: Build Seashell
          command: eval $(opam env) && dune build bin/ex.bc
