version: 2
jobs:
  build:

    docker:
      - image: hseeberger/scala-sbt
    steps:
      - run:
          name: Install g++
          command: |
            apt update
            apt install -y g++
      - checkout
      - restore_cache:
          key: sbt-cache
      - run:
          name: Compile
          command: sbt assembly
      - save_cache:
          key: sbt-cache
          paths:
              - "~/.ivy2/cache"
              - "~/.sbt"
              - "~/.m2"
      - run:
          name: Test
          command: sbt test
